apiVersion: v1
kind: Service
metadata:
  name: subscriber
  namespace: marine-edge
  labels:
    app: subscriber
spec:
  selector:
    app: subscriber
  ports:
    - name: metrics
      protocol: TCP
      port: 8002
      targetPort: 8002
    - name: health
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
