FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY parser/ ./parser/
COPY config/ ./config/
COPY data/ ./data/
COPY main.py .

RUN mkdir -p /app/output

CMD ["python", "main.py", "data/data_source.fit"]
