FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY parser/ ./parser/
COPY config/ ./config/
COPY subscriber.py .

RUN mkdir -p /app/output

EXPOSE 8002
EXPOSE 8081

CMD ["python", "subscriber.py"]
