apiVersion: batch/v1
kind: Job
metadata:
  name: publisher
  namespace: marine-edge
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: publisher
    spec:
      restartPolicy: OnFailure
        #initContainers:
        #- name: wait-for-subscriber
        #  image: python:3.12-slim
        #  command:
        #    - python
        #    - -c
        #    - |
        #      import time
        #      import urllib.request
        #
        #      url = "http://subscriber:8081/health/ready"
        #
        #      while True:
        #          try:
        #              response = urllib.request.urlopen(url, timeout=2)
        #              if response.status == 200:
        #                  print("Subscriber is READY")
        #                  break
        #          except Exception:
        #              print("Waiting for subscriber readiness...")
        #          time.sleep(2)
      containers:
        - name: publisher
          image: marine_edge_platform-publisher:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /app/config/config.json
              subPath: config.json
            - name: publisher-data
              mountPath: /app/output
      volumes:
        - name: config
          configMap:
            name: marine-config
        - name: publisher-data
          persistentVolumeClaim:
            claimName: publisher-data
